const images = {
    default_img: 'http://deshpro.b0.upaiyun.com/deshpro_public/default_img.png',
    ios_app: '/images/ios_app.png',
    andorid: '/images/andorid.png',
    download_close: '/images/download_close.png',
    empty_image: '/images/empty_ticket.png',
    cart: '/images/cart.png',
    is: '/images/is>.png',
    Android: '/images/Android.png',
    iPhone: '/images/iPhone.png',
    safari: '/images/safari12.png',
    load_yaoqing: '/images/load_yaoqing.png',
    bottomarea: '/images/bottomarea.png',
    sign_close_gray: '/images/sign_close_one.png',
    sign_eye_open: '/images/sign_eye_open.png',
    sign_eye:'/images/sign_eye.png',
    croup_receive:'/images/croup_receive.png',
    like_gray : '/images/like_gray.png',
    home_avatar:'/images/home_avatar.png',
    reply:'/images/reply.png',
    bg_music:'/images/bg_music.png',
    bg_music_close:'/images/bg_music_close.png',
    sign_return: '/images/sign_retrun.png',

    macau: {
        search: '/images/macau/search.png',
        book: '/images/macau/book.png',
        entertainment: '/images/macau/entertainment.png',
        food: '/images/macau/food.png',
        gift: '/images/macau/gift.png',
        hotel: '/images/macau/hotel.png',
        rate_exchange: '/images/macau/rate_exchange.png',
        store: '/images/macau/store.png',
        viewpoint: '/images/macau/viewpoint.png',
        location: '/images/macau/location.png',
        call: '/images/macau/call.png',
        rate1: '/images/macau/rate1.png',
        rate2: '/images/macau/rate2.png',
        down: '/images/macau/down.png',
        down2: '/images/macau/down2.png',
        night: '/images/macau/night.png',
        right: '/images/macau/right.png',
        star: '/images/macau/star.png',
        up: '/images/macau/up.png',
        price1: '/images/macau/price1.png',
        price2: '/images/macau/price2.png',
        price1_red: '/images/macau/price1_red.png',
        price2_red: '/images/macau/price2_red.png',
        callPhone: '/images/macau/callPhone.png',
        notRoom: '/images/macau/notRoom.png',
        bg_music: '/images/macau/bg_music.png',
        bg_music_close: '/images/macau/bg_music_close.png'
    },
    navigation2: {
        weather: '/images/navigation/weather.png',
        round_trip: '/images/navigation/round_trip.png',
        fast_food: '/images/navigation/fast_food.png',
        convenient: '/images/navigation/convenient.png',
        hotline: '/images/navigation/hotline.png'
    },
    social:{
        like_gray: '/images/social/like_gray.png'
    },

    out_exit: '/images/out_exit.png'
}
export default images